apiVersion: apps/v1
kind: Deployment
metadata:
  name: first-deployment
  # namespace: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: first-pod
  template:
    metadata:
      labels:
        app: first-pod
    spec:
      containers:
        - name: jwt-app
          image: demojwtimage
          imagePullPolicy: Never
          # securityContext:
          #   capabilities:
          #     drop: 
          #       - all
          #     all:
          #       - chown
          #     allowPrivilegeEscalation: false
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 4001
            - containerPort: 4002

